name: 'Phx Build And Deploy Composite Action'
description: 'Execute Build And Deploy Operations In A Composite Action'
inputs:
  secrets:
    description: 'Secrets'
    required: true
  actionInputs:
    description: 'Inputs'
    required: true
  enable-extended-ops:
    type: boolean
    description: Enable Extended Ops
outputs:
  json-action-outputs:
    description: "Json Composite Action Outputs"
    value: ${{ toJSON(steps.json-ops.outputs) }}
  json-action-extended-outputs:
    description: "Json Composite Action Outputs"
    value: ${{ toJSON(steps.json-extended-ops.outputs) }}    
  has-extended-outputs:
    description: "Has Json Extended Composite Action Outputs"
    value: ${{ steps.json-extended-ops.outputs.has-extended-ops-results || false }}
runs:
  using: "composite"
  steps:
    - name: Calculate New Build Number
      shell: bash
      run: |
          newBuildNumber=$(echo $((${{env.buildNumberBase}}+${{github.run_number}})))
          echo "New Build Number: $newBuildNumber"
          echo "newBuildNumber=$newBuildNumber" >> $GITHUB_ENV   
          
    - name: Build
      shell: bash
      env:
        SECRET1: ${{ fromJSON(inputs.secrets).DESC }}
        IS_ENTERPRISE_APP: ${{ fromJSON(inputs.actionInputs).enterprise-app }}
        RUNNER: ${{ fromJSON(inputs.actionInputs).runner }}
      run: |
        echo "Building..."
        echo "Archive Path: ${ARCHIVE_PATH}"          
        echo "Workflow: ${{github.workflow}}"
        # echo "appVersion: $appVersion"
        # echo "newBuildNumber: ${newBuildNumber}"
        echo "Is Enterprise App: ${IS_ENTERPRISE_APP}"        
        echo "Runner ${RUNNER}"
        if ${IS_ENTERPRISE_APP} == "true"; then
          echo "Enterprise App"
          ./scripts/deploy.sh -b "${newBuildNumber}" -v "$appVersion" -S "iPhone Distribution: Phoenix Roberts LLC" -M dae3007d-dbd8-4f85-bfbd-5cbef813cd3b -s "Enterprise MemoryMatrix" -c "Enterprise Release" -i "${ARCHIVE_PATH}"
        else
          echo "App Store App"
          ./scripts/deploy.sh -b "${newBuildNumber}" -v "$appVersion" -S "Apple Distribution: Robert Zmudzinski (LK58XLFP48)" -M cc7c62a4-7417-4578-b2f0-30b5f8fd50fe -s "MemoryMatrix" -c "Release" -i "${ARCHIVE_PATH}"
        fi          

    - name: Package
      shell: bash
      env:
        SECRET1: ${{ fromJSON(inputs.secrets).DESC }}
        IS_ENTERPRISE_APP: ${{ fromJSON(inputs.actionInputs).enterprise-app }}
        RUNNER: ${{ fromJSON(inputs.actionInputs).runner }}    
        JOB_TYPE: ${{ fromJSON(inputs.actionInputs).job-type }}    
      if: env.IS_ENTERPRISE_APP == 'true'
      run: |          
        echo "Packaging For Job Type: ${JOB_TYPE}"
        if ${IS_ENTERPRISE_APP} == "true"; then
          echo "Creating Enterprise Package..."
          xcodebuild -exportArchive -archivePath "${ARCHIVE_PATH}" -exportPath "${IPA_PATH}" -exportOptionsPlist ./export-enterprise.plist
        else 
          echo "Creating App Store Package..."
          xcodebuild -exportArchive -archivePath "${ARCHIVE_PATH}" -exportPath "${IPA_PATH}" -exportOptionsPlist ./export-appstore.plist     
        fi
        echo "Workflow: ${{github.workflow}}" > "${IPA_PATH}/changes.txt"
        echo "appVersion: $appVersion" >> "${IPA_PATH}/changes.txt"
        echo "newBuildNumber: ${newBuildNumber}" >> "${IPA_PATH}/changes.txt"
        find "${ARCHIVE_PATH}" -name "*" > results.txt
        find "${IPA_PATH}" -name "*" >> results.txt  
